// <auto-generated />
using System;
using DGII_CNTR.ContextDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DGII_CNTR.Migrations
{
    [DbContext(typeof(DgiiDbContext))]
    partial class DgiiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DGII_CNTR.Model.ComprobantesFiscales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ContribuyentesIdContribuyente")
                        .HasColumnType("int");

                    b.Property<int>("IdContribuyente")
                        .HasColumnType("int");

                    b.Property<string>("NCF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("itbis18")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("rncCedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContribuyentesIdContribuyente");

                    b.ToTable("comprobantesF");
                });

            modelBuilder.Entity("DGII_CNTR.Model.Contribuyentes", b =>
                {
                    b.Property<int>("IdContribuyente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContribuyente"), 1L, 1);

                    b.Property<string>("estatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rncCedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdContribuyente");

                    b.ToTable("Contribuyente");
                });

            modelBuilder.Entity("DGII_CNTR.Model.ComprobantesFiscales", b =>
                {
                    b.HasOne("DGII_CNTR.Model.Contribuyentes", null)
                        .WithMany("ComprobantesFiscales")
                        .HasForeignKey("ContribuyentesIdContribuyente");
                });

            modelBuilder.Entity("DGII_CNTR.Model.Contribuyentes", b =>
                {
                    b.Navigation("ComprobantesFiscales");
                });
#pragma warning restore 612, 618
        }
    }
}
